import os

FLASK_HOST = "0.0.0.0"
FLASK_PORT = os.getenv("FLASK_PORT", 50000)
FLASK_POST = "POST"
FLASK_GET = "GET"
FLASK_DATABASE_PATH_KEY = "FLASK_DATABASE_PATH"

DEFAULT_RATE_LIMIT = "50 per day"

CONSOLE_LOG_LEVEL = os.getenv("CONSOLE_LOG_LEVEL", "INFO")
FILE_LOG_LEVEL = os.getenv("FILE_LOG_LEVEL", "DEBUG")
